### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by patrick-kidger** [google-research/torchsde#47]
Creating a list of features that are nice to have, but aren't necessarily a priority right now.

- [ ] Add static tensors as an input to `sdeint`, `sdeint_adjoint`
- [ ] Use batch-vjp to compute `dg_ga`, if and when batch-vjp ever becomes available.
- [ ] Add Milstein for general noise, using Levy area approximation.
- [ ] Stratonovich adjoint support for additive/scalar/diagonal noise.
- [ ] Better adaptivity checks. (e.g. general-noise Heun should be possible with adaptive stepping, I believe.)
- [ ] Allow an `fg` function on SDEs, that computes drift+diffusion simultaneously.
    - If it's not specified then it is added to the SDE in the obvious naive way.
    - The solvers are modified to use `fg` where appropriate.
    - Very often we want to compute drift and diffusion at the same location, and they may share computational structure, so this gives improved efficiency.
    - It gives a nice way to add `logqp` back: it can be done by wrapping the SDE with something implementing this function, which means the modified drift can be calculated without requerying the diffusion.
    - In much the same way, it gives a way to perform Ito<->Strat conversions, if that's ever a thing we want to consider.
    - I've not thought how this might interact with things like `g_prod` and the adjoint etc; possibly there are hurdles there.

**Comment by jparkhill** [comment]
My number one desired feature is antithetic sampling as an option for sdeint. It's pretty cumbersome to achieve this without editing the package by changing the BrownianInterval's W.

**Comment by patrick-kidger** [comment]
I've not filled in every detail, but I'd have thought something like this should work:

```
class AntitheticBrownian(BaseBrownian):
   def __init__(self, bm):
       self.bm = bm

    def __call__(self, ta, tb):
        return -self.bm(ta, tb)

bm = BrownianInterval(...)
ys = torchsde(bm=bm, ...)

abm = AntitheticBrownian(bm)
ays = torchsde(bm=abm, ...)

ys = torch.cat([ys, ays])
```

Does this approach fail / are you trying to achieve something beyond this?

**Comment by patrick-kidger** [comment]
I've not filled in every detail, but I'd have thought something like this should work:

```python
class AntitheticBrownian(BaseBrownian):
   def __init__(self, bm):
       self.bm = bm

    def __call__(self, ta, tb):
        return -self.bm(ta, tb)

bm = BrownianInterval(...)
ys = torchsde(bm=bm, ...)

abm = AntitheticBrownian(bm)
ays = torchsde(bm=abm, ...)

ys = torch.cat([ys, ays])
```

Does this approach fail / am I missing something / are you trying to achieve something beyond this?

**Comment by jparkhill** [comment]
Does work, but it's still much uglier than it needs to be vs sdeint(...,antithetic=True). For innumerable financial applications of this library, this type of option is... _priceless_ ;p Here's a filled in version in case anyone else is following along: 

`sde = GBM(sigma0=.22)
ts = tch.linspace(0,1.,365)
ntraj = 1000
bm = torchsde.BrownianInterval(ts[0], ts[-1], size=(ntraj,sde.brownian_size), levy_area_approximation='space-time')
ys_ = torchsde.sdeint(sde,sde.y0(ntraj=ntraj), ts, bm=bm)
class AntitheticBrownian(torchsde.BrownianInterval):
    def __init__(self, t0, t1, size, bm):
        super(AntitheticBrownian, self).__init__(t0,t1,size, levy_area_approximation='space-time')
        self.bm = bm
    def __call__(self, ta, tb=None, return_U=False, return_A=False):
        Z = self.bm(ta, tb, return_U, return_A)
        if return_U:
            if return_A:
                return -Z[0], Z[1], Z[2]
            else:
                return -Z[0], Z[1]
        else:
            if return_A:
                return -Z[0], Z[1]
            else:
                return -Z
abm = AntitheticBrownian(ts[0], ts[-1], (ntraj,sde.brownian_size), bm)
ays = torchsde.sdeint(sde,sde.y0(ntraj=ntraj), ts, bm=abm)
ys = torch.cat([ys_, ays],0)`
